### ISSUE TITLE
Starjacking

### ISSUE THREAD

**Issue by AnthonyHerman** [SAP/risk-explorer-for-software-supply-chains#17]
https://checkmarx.com/blog/starjacking-making-your-new-open-source-package-popular-in-a-snap/

**Comment by henrikplate** [comment]
Hello @AnthonyHerman, Thank you for posting this link, this technique is certainly useful for attackers to promote malicious packages. I tend to adding this link not as its own attack vector, but as complementary info to the two existing vectors `Develop and Advertise Distinct Malicious Package from Scratch` and `Create Name Confusion with Legitimate Package`. What do you think?

**Comment by AnthonyHerman** [comment]
Sounds reasonable to me @henrikplate
