### ISSUE TITLE
New or existing attack vector "Omit scope/namespace"

### ISSUE THREAD

**Issue by henrikplate** [SAP/risk-explorer-for-software-supply-chains#26]
Suppose a legitimate npm package `@foo/bar`, attackers can deploy a malicious package `bar` to trick users. This could also work in other ecosystems having scopes or namespaces.

**Comment by piergiorgioladisa** [comment]
Indeed this was the case of the Java samples from Backstabber's Knife Dataset (e.g., [maven-compiler-plugin@3.9.0](https://search.maven.org/artifact/com.github.codingandcoding/maven-compiler-plugin/3.9.0/jar)). I am in doubt whether to create a new attack vector or add this case to Brandjacking (as you said), thus extending the definition of the latter. I am more in favor of this last option.

**Comment by henrikplate** [comment]
Alright, let's broaden the definition of brandjacking to also cover this case. So far, its idea was to add a well-known prefix to a non-existing package, e.g., `aws-foo`. In the future, it would also cover publishing a package with an existing name but without the scope (brand).

**Comment by henrikplate** [comment]
I changed my mind and propose a new attack vector "Omitting Scope or Namespace", see #29. The reason is that this is not really about company brands, the omitted scope or namespace could be anything.
