### ISSUE TITLE
Update: IconBurst NPM software supply chain attack grabs data from apps and websites

### ISSUE THREAD

**Issue by piergiorgioladisa** [SAP/risk-explorer-for-software-supply-chains#28]
https://blog.reversinglabs.com/blog/iconburst-npm-software-supply-chain-attack-grabs-data-from-apps-websites

For what I see there from the name of the malicious packages I would say that they match the case of [Similarity Attack](https://sap.github.io/risk-explorer-for-software-supply-chains/#/attacktree?av=AV-207)

**Comment by henrikplate** [comment]
The attackers published many packages with names changed according to several techniques. Maybe it makes sense to link this example to parent node "Create Name Confusion"?

**Comment by henrikplate** [comment]
Implemented with #30
