### ISSUE TITLE
Safeguard: Binary Transparency

### ISSUE THREAD

**Issue by kpcyrd** [SAP/risk-explorer-for-software-supply-chains#53]
hi!

I noticed the list of safeguards is missing Binary Transparency, the general concept is explained [here by mozilla](https://wiki.mozilla.org/Security/Binary_Transparency) (ignore the specific implementation details described there), [rekor](https://github.com/sigstore/rekor) is one of the implementations for a signature transparency log and [pacman-bintrans](https://github.com/kpcyrd/pacman-bintrans) is an experimental integration between rekor and pacman, the Arch Linux package manager.

Would be cool if Binary Transparency could be added to the list!

**Comment by piergiorgioladisa** [comment]
> hi!
> 
> I noticed the list of safeguards is missing Binary Transparency, the general concept is explained [here by mozilla](https://wiki.mozilla.org/Security/Binary_Transparency) (ignore the specific implementation details described there), [rekor](https://github.com/sigstore/rekor) is one of the implementations for a signature transparency log and [pacman-bintrans](https://github.com/kpcyrd/pacman-bintrans) is an experimental integration between rekor and pacman, the Arch Linux package manager.
> 
> Would be cool if Binary Transparency could be added to the list!

Thank you once more @kpcyrd for opening this issue and following discussion. By reading the resource you shared it seems to me a more sophisticated version of the current safeguard `[SG-043] Integrity check of dependencies through cryptographic hashes`. What do you think then to add the resources you shared as references for this particular safeguard and maybe improve also the description of `SG-043` to include not only the concept of *cryptographic hashes* but also the concept of *transparency logs*?
