### ISSUE TITLE
Add "npm packages used by crypto exchanges compromised" 

### ISSUE THREAD

**Issue by piergiorgioladisa** [SAP/risk-explorer-for-software-supply-chains#54]
[npm packages used by crypto exchanges compromised](https://www.bleepingcomputer.com/news/security/npm-packages-used-by-crypto-exchanges-compromised/)

**Comment by piergiorgioladisa** [comment]
The article says that root causes still have to be determined, but apparently the attack happened by deploying a malicious versions directly in npm (and not in the GitHub repo) through the account of one employee of dYdX crypto platform.

**Comment by henrikplate** [comment]
[AV-602] Take-over Legitimate Account
