### ISSUE TITLE
Attack: Another case where ownership has been transferred

### ISSUE THREAD

**Issue by henrikplate** [SAP/risk-explorer-for-software-supply-chains#66]
https://www.theregister.com/2021/01/07/great_suspender_malware/

**Comment by piergiorgioladisa** [comment]
For what I understand here the ownership transfer caused the injection of malicious code into a single project of the Great Suspender add-on. 

I don't understand how this reference fits the scope of the taxonomy, namely "the attacker's top-level goal is to place malicious code in open-source artifacts such that it is executed in the context of downstream projects, e.g., during its development or runtime."

**Comment by henrikplate** [comment]
Do you mean it does not fit because there are no downstream development projects but directly the end-user's runtime (browser)? That is true, however, we did not follow that too strictly in the past either. The CCleaner and SolarWinds attacks are also about (commercial) software directly intended for end-users. What I find interesting about the Great Suspender incident is the monetary aspect (in comparison to event-stream, where the attacker only had to ask politely).
