### ISSUE TITLE
[New Attack Vector] AI Package Hallucination

### ISSUE THREAD

**Issue by piergiorgioladisa** [SAP/risk-explorer-for-software-supply-chains#88]
Probably you've heard about the [AI Package Hallucination](https://vulcan.io/blog/ai-hallucinations-package-risk) strategy. In a nutshell, as per my understanding, LLMs can "invent" names of packages when users ask to generate some code. Thus, attackers may deploy malicious packages under such names.

I personally think this could be included as a [Create Name Confusion with Legitimate Package](https://sap.github.io/risk-explorer-for-software-supply-chains/#/attacktree?av=AV-200)  technique. But before creating a PR to add this new AV, I would like to hear your opinion @henrikplate @serenaponta

**Comment by henrikplate** [comment]
I think it is a relevant new technique, and since the hallucinated package name probably repeats the name of some technology the user asked about (as in the case of `arangodb`), it's fair to add it below "Create Name Confusion".

**Comment by piergiorgioladisa** [comment]
Great! Then I will create a PR and of course feel free to adjust it if you find some inconsistency or mistake
