### ISSUE TITLE
Description of AV-208 is hard to understand

### ISSUE THREAD

**Issue by copernico** [SAP/risk-explorer-for-software-supply-chains#91]
Without some context or an example, the description of AV-208 is hard to understand.
In particular, it is unclear what it means to "omit the scope" (what scope? omit from where?)
I suspect this might be only relevant for some ecosystems?

**Comment by henrikplate** [comment]
Old description of AV-208, Omitting Scope or Namespace: This technique consists of taking the name of a package with scope (or namespace) and publishing it without the scope.

Proposed change: Some package repositories support namespaces as optional element of a package identifier. Each user and organization on npm, for instance, has its own scope. Namespaces are typically used by individuals, organizations or projects to group and manage multiple artifacts, and indicate ownership to potential consumers. Attackers can publish a package with identical name but without namespace in the hope that victims wrongly believe it comes from the trusted organization or project.

**Comment by piergiorgioladisa** [comment]
Closing the issue as it has been fixed by @henrikplate
